// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import financial.bian.attribute.groups.common as common;

// public type LocationDirectoryEntryOk record {|
//     *http:Ok;
//     # body
//     LocationDirectoryEntry body;
// |};

# "An assertion or statement with regard to a concept, a characteristic.
#
# Examples: Product pricing rules, Customer reference details
#
# A descriptor can be atomic or composed."
# Prospect Management
public type Occupancy record {
    # Reference to the bank customer (if they are owner and/or occupier of the property at the location)
    common:Involvedparty CustomerReference?;
    # Reference to the bank customer (if they are owner and/or occupier of the property at the location)
    # LocationOwnerTitle
    common:Involvedparty LocationOwnerTitle?;
    # The estimated (book) value of the property at the location - rental and purchase as appropriate
    # LocationValue
    string LocationValue?;
    # The type of occupancy (e.g. residency, business, retail, entertainment)
    string LocationOccupierType?;
    # Reference to the bank customer (if they are owner and/or occupier of the property at the location)
    common:Involvedparty LocationOccupierReference?;
    # Nature of the access terms or entitlement of the occupier (e.g. leasehold, rental, public access)
    # LocationOccupierTerms
    LocationArrangement LocationOccupierTerms?;
    # Reference to the bank customer (if they are owner and/or occupier of the property at the location)
    common:Involvedparty AlliancePartnerReference?;
};

# "An assertion or statement with regard to a concept, a characteristic.
#
# Examples: Product pricing rules, Customer reference details
#
# A descriptor can be atomic or composed."
# Prospect Management
public type Use record {
    # The planning or zoning status (e.g. residential, commercial, industrial)
    string LocationZoningType?;
    # The allowed usage for the property at the location (e.g. domestic residence, manufacturing, retail)
    LocationUsage LocationUsage?;
};

# Nature of the access terms or entitlement of the occupier (e.g. leasehold, rental, public access)
public type LocationArrangement record {
    # ArrangementAction
    common:Action ArrangementAction?;
    # ArrangementStartDate
    common:Datetime ArrangementStartDate?;
    # ArrangementEndDate
    common:Datetime ArrangementEndDate?;
    # ArrangementStatus
    common:Arrangementstatus ArrangementStatus?;
    # ArrangementSubjectMatter
    common:Subject ArrangementSubjectMatter?;
    # * `SweepArrangement` - An arrangement into which is promised for the set-up and execution of structured sweeps to and from the facility to a linked account.
    # * `WithdrawalArrangement` - An arrangement into which is promised to deliver Withdraw Service  to take fund out of an account. 
    # * `DepositArrangement` - An arrangement into which is promised to deliver Deposit Service  to place funds into an account for safekeeping. 
    # * `InterestArrangement` - An arrangement into which is promised to apply a pricing element expressed in a percentage  to a principal amount.
    # * `FeeArrangement` - An arrangement into which is promised to apply a charge for services rendered. 
    # * `LienArrangement` - An arrangement into which is promised for placing a lien or block on the account for a specified purpose, amount, and period. 
    # * `InformationArrangement` - An arrangement concerning the information the bank will provide about the agreement/account
    # * `PaymentArrangement` - An arrangement into which is promised to deliver a specific payment service including regular payments, standing orders, direct debits and bill pay instructions. 
    # * `EntitlementArrangement` - Right or obligation linked to the involvement of a party in an agreement
    # * `PeriodArrangement` - 
    # * `CollateralArrangement` - An arrangement into which is promised for handling the oversight of the allocation, valuation and administration of collateral associated with the facility. 
    # * `LimitArrangement` - An arrangement to limit something
    # e.g., the number of transaction per week, the amount of money allowed to withdraw per week/day and etc. 
    # * `AccessArrangement` - An arrangement that allows or restricts the access to a service or product, channel or device through a specific access point
    # * `CardPaymentArrangement` - An arrangement into which is promised to deliver Card payment Service to execute payment transactions through a payment card, including online payments. 
    # * `StandingOrderArrangement` - An arrangement into which is promised to deliver Standing Order Service to make regular transfers on given dates to a named beneﬁciary. 
    # * `OverdraftArrangement` - An arrangement into which is promised to deliver Overdraft Service  that allows fund transfer even if there is no provision on the account. 
    # * `RepaymentArrangement` - An arrangement into which is promised for paying back money previously borrowed from a lender. 
    # * `StatementArrangement` - An arrangement into which is promised to deliver a reporting service on payment transactions registered on an account. 
    # * `CreditTransferArrangement` - An arrangement into which is promised to allow a payer to transfer fund to a beneficiary. 
    # * `ProductAndServiceArrangement` - 
    # * `FactoringArrangement` - 
    # * `RolloverArrangement` - Arrangement stipulating the modalities for an automatic renewal of the agreement
    #
    # i.e. the replacement of the agreement with a new one without renewed negociation and witout explicit agreement of the customer 
    # * `RestructuringArrangement` - 
    # * `InsuranceArrangement` - 
    # * `CollectionArrangement` - An arrangement into which is promised to collect past-due debts from borrowers
    # * `UnderwritingArrangement` - A contractual agreement between parties that commits the underwriter to assuming risk.
    # * `TerminationArrangement` - 
    # * `MaturityArrangement` - 
    # * `AdministrativeArrangement` - 
    common:Arrangementtypevalues Arrangementtype?;
    # ArrangementIdentification
    common:Identifier ArrangementIdentification?;

};

# The allowed usage for the property at the location (e.g. domestic residence, manufacturing, retail)
public type LocationUsage record {
    # The purpose or usage of  location in relationship to the associated object like the mailing address for letters or URL for email address.  
    string LocationUsage?;
};

# Capture and maintain reference information about some type of entitity within Location Data Management.
public type LocationDirectoryEntry record {
    # LocationReference
    common:Location LocationReference?;
    # >
    # * `OpenDate` - 
    # * `RefreshDate` - 
    common:Directoryentrydatetypevalues DirectoryEntryDateType?;
    # DirectoryEntryDate
    common:Datetime DirectoryEntryDate?;
};
