serverUrl = "http://localhost:9191/backend"
port = 9092
financialGatewayOutboundInitiateUrl = "/FinancialGateway"
correspondenceOutboundInitiateUrl = "/Correspondence/Outbound/Initiate"
correspondenceOutboundWithResponseInitiateUrl = "/Correspondence/OutboundWithResponse/Initiate"
